# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bieres.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ListeBiere(object):
    def setupUi(self, ListeBiere):
        ListeBiere.setObjectName("ListeBiere")
        ListeBiere.resize(581, 309)
        ListeBiere.setMinimumSize(QtCore.QSize(581, 309))
        ListeBiere.setMaximumSize(QtCore.QSize(581, 309))
        self.centralwidget = QtWidgets.QWidget(ListeBiere)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 20, 142, 28))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 80, 50, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 120, 83, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 160, 68, 18))
        self.label_4.setObjectName("label_4")
        self.nom = QtWidgets.QLineEdit(self.centralwidget)
        self.nom.setGeometry(QtCore.QRect(390, 80, 171, 21))
        self.nom.setObjectName("nom")
        self.variete = QtWidgets.QLineEdit(self.centralwidget)
        self.variete.setGeometry(QtCore.QRect(390, 120, 171, 21))
        self.variete.setObjectName("variete")
        self.degre = QtWidgets.QLineEdit(self.centralwidget)
        self.degre.setGeometry(QtCore.QRect(390, 160, 171, 21))
        self.degre.setObjectName("degre")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 220, 161, 19))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 237, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        ListeBiere.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ListeBiere)
        self.statusbar.setObjectName("statusbar")
        ListeBiere.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(ListeBiere)
        self.toolBar.setObjectName("toolBar")
        ListeBiere.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(ListeBiere)
        QtCore.QMetaObject.connectSlotsByName(ListeBiere)

    def retranslateUi(self, ListeBiere):
        _translate = QtCore.QCoreApplication.translate
        ListeBiere.setWindowTitle(_translate("ListeBiere", "MainWindow"))
        self.label.setText(_translate("ListeBiere", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Formulaire</span></p></body></html>"))
        self.label_2.setText(_translate("ListeBiere", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">Nom :</span></p></body></html>"))
        self.label_3.setText(_translate("ListeBiere", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">Varièté :</span></p></body></html>"))
        self.label_4.setText(_translate("ListeBiere", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">Degré : </span></p></body></html>"))
        self.pushButton.setWhatsThis(_translate("ListeBiere", "<html><head/><body><p align=\"center\">Créer</p></body></html>"))
        self.pushButton.setText(_translate("ListeBiere", "Créer"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ListeBiere", "Bière"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ListeBiere", "Variété"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ListeBiere", "Degré"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("ListeBiere", "1664"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("ListeBiere", "Blonde"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("ListeBiere", "3.4"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.toolBar.setWindowTitle(_translate("ListeBiere", "toolBar"))

